server:
  port: 8080

spring:
  application:
    name: flashpage

  profiles:
    active: dev

  jackson:
    time-zone: America/Argentina/Buenos_Aires
    date-format: dd-MM-yyyy HH:mm:ss
